### ISSUE TITLE
[App registration] SVG problem

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#561]
SVGs mess up email marketing down the line. We need either: 
1. A solution that takes any final input and makes them interoperable 
2. Exclude SVGs in the form and validate only certain file types. And update the instructions. 

cc @aulneau

**Comment by aulneau** [comment]
> A solution that takes any final input and makes them interoperable

this is already the case, any image that is uploaded we process with imgix, and if we aren't, we should be able to. cc @hstove

**Comment by jeffdomke** [comment]
That is what I thought and that is why you were tagged :)

**Comment by markmhx** [comment]
@jeffdomke what App.co emails in particular do you have in mind here? The weekly "new apps" mailer? I believe we have already implemented SVG conversion there.

**Comment by jeffdomke** [comment]
@cuevasm is the one that mentioned the svgs breaking in the emails.

**Comment by GinaAbrams** [comment]
This is still an issue, where app.co does not accept SVG images even though it says it does. Can we change the text to not include SVGs @markmhx

**Comment by markmhx** [comment]
@aulneau mind checking if your prior imgix proposal is a quick fix here?
